### ISSUE TITLE
Bad name for place "related_name" in Equipment Model

### ISSUE THREAD

**Issue by Maxime-M** [eost/gissmo#103]
Related name for place in Equipment model is bad:

```python
from place.models import Place

place = Place.objects.first()
place.current_place.all() # Returns an Equipment queryset
```
`place` related_name should be changed from `current_place` to `equipments`

**Comment by blankoworld** [comment]
Same other elements that go wrong:

  * sending_place from Equipment
  * send_to from EquipmentHistory
  * default from Station
  * default from Place

They need to be changed.
