### ISSUE TITLE
Bug in intervention

### ISSUE THREAD

**Issue by heleneomp** [eost/gissmo#115]
Lors d'une intervention sur un site, si on ajoute plusieurs actions dans "Equipment Intervention", à la sauvegarde seul la première ligne est prise en compte.

**Comment by mbdb** [comment]
Exact, j'ai reproduit le problème, il s'agit bien d'un bug. @fabienengels ??? 
Il semble impossible de contourner le problème, si ce n'est en créant une intervention par "Equipement Intervention", ce qui n'est pas bon.
De plus, la modification à posteriori d'une intervention (pour rajouter une ligne "Equipement Intervention") renvoie l'erreur "Another intervention already exists with same date and same equipment".

**Comment by blankoworld** [comment]
Après avoir listé les changements effectués depuis la version 1.8 - et testé rapidement la suppression d'une des modifications - il semble que le bug soit présent depuis le ticket #106 .
Je regarde encore aujourd'hui pour avoir plus de détails sur ce problème.
