### ISSUE TITLE
prise en compte que d'une seule action dans intervention site "EOST", gissmo 1.9

### ISSUE THREAD

**Issue by helenejund** [eost/gissmo#127]
je voudrai effectuer plusieurs actions de type "test" pour une liste d'équipement dans une seule intervention, mais j'ai l'impression qu'il n'y a qu'une seule action qui est finalement enregistrer. j'ai déjà fait cette manip auparavant sans soucis, cela permettait de limiter le nombres des interventions, mais là ça passe plus.

Voici l'intervention en question: EOST : 2016-09-21 10:00:00
je voudrai y ajouter le test d'autres chargeurs mascot pour changer leur station de "to be tested" à "availaible" . J'ai fait deux essaies, il n'y a que le premier chargeur qui semble changer de statut.

**Comment by blankoworld** [comment]
Même problème que le ticket #115 .
