### ISSUE TITLE
Historique des canaux (objets ? ) supprimés

### ISSUE THREAD

**Issue by bonaime** [eost/gissmo#13]
Je viens de supprimer des canaux que j'avais mis en test. Dans mon historique sur la droite, je vois encore des "restes" de ces canaux et bien sur quand je clique dessus, il y a une erreur car les objets n'existent plus => Quand on supprime un canal (peut etre que c'est pareil pour les autres objets ? ) il faudrait supprimer sa (ses) références dans l'historique.

![capture decran 2013-10-16 a 16-10-13 10 40 34](https://f.cloud.github.com/assets/750709/1340936/adadd250-363e-11e3-834b-4e59e45f7d97.png)
![capture decran 2013-10-16 a 16-10-13 10 40 08](https://f.cloud.github.com/assets/750709/1340937/b147a81e-363e-11e3-86b9-4c9c629616d7.png)

**Comment by blankoworld** [comment]
La fonctionnalité d'historique sur la page d'accueil semble peu utilisée dans Gissmo. Et n'apporte que très peu d'informations puisque cela montre à chaque utilisateur les 10 dernières actions qu'il a effectué.

Je pense qu'il est plus sage de l'enlever. Nous avons prévu un système d'historique plus précis dans les versions Gissmo 2.0 et supérieures.
