### ISSUE TITLE
Server Error (500) à l'ajout d'un équipement

### ISSUE THREAD

**Issue by mbdb** [eost/gissmo#136]
On gissmo 2.0-rc4:
Impossible d'ajouter un nouvel équipement, le serveur renvoie:
Server Error (500)

Testé avec utilisateur "user" et "maxime.besdeberc"

**Comment by mbdb** [comment]
Même problème lorsque je veux configurer l' "acquisition chain": la même erreur ressort lorsque je sélectionne une valeur dans le menu déroulant "Connected to" et que j'ajoute un équipement.

**Comment by blankoworld** [comment]
Note à moi : Sûrement lié à ceci : 

```

**Comment by blankoworld** [comment]
Je réussis à reproduire l'erreur lors de la création initiale d'un équipement en lui donnant directement une destination plutôt qu'une place. L'intervention sur l'équipement ne parvient pas à être créée car il faut un lieu d'intervention.
Comme on envoie l'équipement, j'avais initialement pensé qu'on enlevait le lieu actuel (place), et qu'on ne mettait que le lieu de destination.
Mais c'était sans compter le fait qu'une intervention d'envoi s'effectue physiquement quelque part. Il serait donc sage de garder la place, même pour un envoi.

Je suis donc d'avis de rendre la place obligatoire pour les équipements. Et laisser l'utilisateur ajouter une destination au besoin.

On garde comme ça : 

  * le lieu initial (la place) (ce qui permet aux interventions de se créer correctement)
  * le lieu de destination (ce qui permet de faire la liste des équipements attendus dans un lieu donné)


@mbdb : j'aimerais ton avis sur la question.

**Comment by blankoworld** [comment]
Après en avoir discuté de vive voix, cela semble convenir. J'ai intégré cela dans la version 2.0-rc5 afin de pouvoir tester.
