### ISSUE TITLE
Ajout de Filtre dans l'API

### ISSUE THREAD

**Issue by bouazzouz** [eost/gissmo#179]
Bonjour,
   Est ce qu'il est possible d'ajouter des filtres dans l'API. Si oui! on vous fera une liste dont on a besoin.
Merci!

**Comment by blankoworld** [comment]
Oui c'est possible.

Dans quelle API ? La v2 je suppose ? Si oui, j'ai commité hier soir un exemple pour le champ 'code' de Station, suite à une suggestion de David : Cf. aa3576eab24edaa2293b448630e354d194a5d2e4

**Comment by blankoworld** [comment]
Liste des filtres donnés dans le ticket #183 : 
**Stations** : code
**networks** : code
**channelcodes** : name
**equipments**: place
**agencies**: name
**models** : name
**types** : name et parent
**channels** : equipment , network, code, station
**datatypes** : name
**equipment_states** : name
**equipment_configurations** : equipment, parameter

Je m'occuperais d'ajouter ces filtres courant de la semaine. Je commence demain.

**Comment by blankoworld** [comment]
Pour ces objets cela ne me semble pas nécessaire vu le peu de données : 

  * channelcodes (liste de taille moyenne dont les codes sont uniques)
  * datatypes (la liste n'a jamais évoluée en plus de 2 ans déjà)
  * equipment_states (la liste est courte et le restera)

Sur un client API, il suffit de récupérer **/api/v2/datatypes/?format=json** et de tout mettre dans un dictionnaire au début du programme. Ce qui permet à la fois d'être plus rapide dans le programme, de diminuer le nombre d'appels faits à l'API et de complexifier son code pour chaque fois faire un appel à l'API pour récupérer des informations.

**Comment by blankoworld** [comment]
Dans le cas de equipment_configurations, il faut savoir que ce n'est pas la configuration de l'équipement pour un canal donné. Mais seulement sa configuration par défaut utilisée pour créer de nouveaux canaux.

Il manque donc channel_configurations si vous souhaitez avoir la configuration des équipements pour un canal donné. Mais cet objet est voué à disparaître dans les modifications que je souhaite apporter prochainement.

**Comment by blankoworld** [comment]
Les changements ont été effectués ici : 98e970813f553f5c38dd96c3ccc130884ade6596

Cela ira-t-il @bouazzouz pour les 3 objets dont je parlais sans les filtres (channelcodes, datatypes et equipment_states) ? Si oui merci de m'en informer que je ferme le ticket.

**Comment by bouazzouz** [comment]
Pour ce qui concerne  (channelcodes,  datatypes, equipment_states)  je laisse les filtres dans mon code pour déminuer l'appel à l'API.  Merci pour les autres.

**Comment by blankoworld** [comment]
Ok, je ferme donc le ticket. On peut toujours commenter ici, voire ouvrir à nouveau le ticket si après vos tests quelque chose n'est pas satisfaisant.

**Comment by bouazzouz** [comment]
Pour equipment_configurations la seul chose qui nous intéresse est de pouvoir rentrer  et/ou récupérer le Gain(et éventuellement la valeur Vpp)  associer au Numeréseur(Datalogger). Et c'est le seul moyen qu'on a trouvé pour récupérer cette info.

**Comment by blankoworld** [comment]
Je pense que l'information que vous cherchez n'est pas dans equipment_configurations (configuration par défaut d'un équipement pour l'installation dans de nouveaux canaux).

Mais bel et bien "channel_configurations" que je n'ai pas encore implémenté dans l'API. Notamment parce que je pense que ça va changer au niveau Channel/Configuration. C'est ce sur quoi je travaille en ce moment.

**Comment by bouazzouz** [comment]
En fait moi je doit ajouter/récupérer des informations de l'API et creer un module inetrmédiare entre GISSMO et nos codes.  Dans mes testes j'arrive bien à récupérer l'information (par défaut), la modifié et en rajouter autres!. Je laisse comme ça pour avancer dans mes testes. Si  tu me confirme qu'on  poura avoirs ses infos aprés.

**Comment by blankoworld** [comment]
Oui, ces infos seront récupérable dans l'API, on fera ce qu'il faut pour ça :)

**Comment by bouazzouz** [comment]
Parfait! ;)
