### ISSUE TITLE
Erreur 500 à l'ajout de PLACE.

### ISSUE THREAD

**Issue by bouazzouz** [eost/gissmo#181]
Bonjour,
 J'ai essayé d'ajouter une place via  l'API(2) avec un post et j'ai eu une erreur 500.
Merci

**Comment by blankoworld** [comment]
@bouazzouz : as-tu ajouté la place via l'interface web de l'API ? Ou via un script ? Quelles ont été les données utilisées pour créer cette Place ?

**Comment by bouazzouz** [comment]
Désolé de ne pa sdonnée des details. 
Alors j'ai testé depuis un script: 
{'name': 'PlaceRESIF',
 'type': 'https://gissmo-test.u-strasbg.fr/api/v2/place_types/6', 
'creation_date': '1989-03-01', 
'note': '', 'is_ready':
 'false', 'geology': 
'null', 'ground_type':
 'null', 'contact': '',
 'latitude': '0.1',
 'longitude': '0.2',
 'elevation': '0.3', 
'agencies': [], 'documents': []
}

**Comment by blankoworld** [comment]
J'ai testé également via l'interface Web, j'ai la même erreur.

Je regarde cela demain en journée.

**Comment by blankoworld** [comment]
Information : 

1. le champ "type" est en lecture seule. Mais c'est un champ requis. Voilà pourquoi la création d'une Place renvoie une erreur 500
2. Il manque un "/" à la fin de la ligne suivante : ```'type': 'https://gissmo-test.u-strasbg.fr/api/v2/place_types/6',```
3. Quand requests renvoie une erreur, il semble qu'il y ait un détail pour chaque champ qui bloque dans ```rs.json()```. Je donne un exemple ici : https://gist.github.com/blankoworld/dc43cac421a25e4b7cc3808c8624dc2c (il faut remplacer le contenu de la variable **server** pour attaquer le bon domaine).
