### ISSUE TITLE
Liste des Filtres à ajouter 

### ISSUE THREAD

**Issue by bouazzouz** [eost/gissmo#183]
Bonjour,
 Ci-dessous des Filtres à ajouter. 
 **Stations** : code
**networks** : code
**channelcodes** : name
**equipments**:  place
**agencies**: name
**models** :  name
**types** : name et parent
**channels** :  equipment , network, code, station
**datatypes** : name
**equipment_states** : name
**equipment_configurations** : equipment, parameter 
Merci d'avance

**Comment by blankoworld** [comment]
Ce ticket est un duplicat du #179 , je ferme donc ce ticket et rajoute la liste des filtres dans le ticket #179.
