### ISSUE TITLE
ajouter la saisie d'un champ pour préciser le site d'entreposage

### ISSUE THREAD

**Issue by jihanesayadi** [eost/gissmo#40]
lors de la création d'un equipement/capteur/numeriseur/etc, est il possible d'ajouter la saisie du champ bati pour préciser le site d'entrposage.

exemple: SIte d'entreposage=> EOST=>Salle 416 ou salle petit piler ou autres

**Comment by blankoworld** [comment]
Ceci est une fonctionnalité de base dans Gissmo 2.0 de par la nouvelle structure : un équipement est obligatoirement soit dans un lieu (que ce soit une galerie, un cabanon, etc.) soit en déplacement vers un lieu.
