### ISSUE TITLE
TODO pre-1.6 : Configuration par défaut des équipements

### ISSUE THREAD

**Issue by blankoworld** [eost/gissmo#64]
Le ticket #25 ajoute la possibilité d'avoir une configuration par défaut pour l'équipement.

Dans ce cadre, l'équipement, à sa création, récupère la configuration par défaut du modèle d'équipement. Pour chaque paramètre il prend la valeur à défaut du paramètre.

En revanche, si aucune valeur n'est marquée comme "par défaut", alors l'équipement n'hérite pas du paramètre. Ce qui est normal puisqu'il serait dangereux d'utiliser une des valeurs aléatoirement comme étant celle par défaut pour l'équipement donné.

Ainsi Maxime, si tu pouvais vérifier la liste des paramètres par défaut afin que chaque modèle soit au propre sur ce sujet, ce serait mieux avant la sortie de la version 1.6 de GISSMO.

Par ailleurs je peux fournir la liste des modèles et des paramètres n'ayant pas de valeur par défaut si tu le désires.

**Comment by mbdb** [comment]
Pour activer cette fonctionnalité au std_user, il faut rajouter les droits suivants:
![capture d ecran_2016-07-26_10-40-29](https://cloud.githubusercontent.com/assets/4572310/17131413/b0302e84-531d-11e6-925b-56afd9deb20e.png)

**Comment by blankoworld** [comment]
Voici la liste des modèles d'équipements et leur paramètres n'ayant aucun paramètre par défaut : 

  * Modèle d'équipement : D6BB-DIN, Paramètre : Gain

Il faudrait ajouter une valeur par défaut à ce modèle d'équipement.

**Comment by blankoworld** [comment]
À la vue du message précédent, on peut clore le ticket.
