### ISSUE TITLE
Incohérence des 'Last Place' dans la page 'liste des équipements' et page 'd'1 équipement'

### ISSUE THREAD

**Issue by mbdb** [eost/gissmo#69]
Ex 1: 
carte sim n° 0316140059330
https://gissmo.unistra.fr/gissmo/gissmo/equipment/?q=0316140059330 marque last place = A160A
alors que 
https://gissmo.unistra.fr/gissmo/gissmo/equipment/1163/ marque last place = A210A

Ex 2:
modem n° 00112B00AEB9
https://gissmo.unistra.fr/gissmo/gissmo/equipment/?q=00112B00AEB9 marque last place = A210A
alors que
https://gissmo.unistra.fr/gissmo/gissmo/equipment/1101/ (page de l'équipement) marque last place = EOST

Cela entraine de multiples problèmes pour retrouver les localisations des équipements.
Voir Gauthier (bureau 416) pour les détails.

**Comment by blankoworld** [comment]
Ce cas survient suite à la suppression d'une intervention impliquant cet équipement. Cela coupe la chaîne des interventions ce qui influe sur l'état et la localisation d'un équipement.
Je suggère de mettre à jour l'équipement suite à la suppression d'une intervention l'impliquant.
En revanche cela ne concernera que les suppressions futures.

Ainsi, pour les problèmes survenus à la mi-août, je ne vois que deux solutions possibles : 

  * soit on créer un script à utiliser lors du prochain déploiement
  * soit on met à jour les équipements actuels à l'aide de quelques lignes Python dans un shell GISSMO : 

```python
from gissmo.models import Equipment    
for e in Equipment.objects.all():
  e.last_state = e.get_last_state()
  e.last_station = e.get_last_station()
  e.save()
```

**Comment by blankoworld** [comment]
L'équipement dont le numéro de série est 2525, sur Rivel, a aussi eu le problème et donc a été « réparé » par l'utilisation de la commande donnée ci-avant.
