### ISSUE TITLE
pb avec la fréquence d'échantillonnage

### ISSUE THREAD

**Issue by wodling** [eost/gissmo#83]
Hello

Lorsque je saisie la fréquence d'échantillonnage pour 3 channels, elle reste figé à 100 Hz et ne prend pas en compte ma valeur de 200 Hz (station CIEL) 

Merci

Hervé

**Comment by blankoworld** [comment]
Il y a effectivement un problème sur la fréquence d'échantillonnage pour la saisie de 3 canaux. Le comportement - non voulu - est de prendre une valeur par défaut en fonction du canal choisit par l'utilisateur. Par exemple pour EH, il suggère 100 Hz et y reste quoique l'utilisateur rentre.

Il faut que la saisie de l'utilisateur puisse prendre le dessus sur cette valeur par défaut. Tant qu'elle ne sort pas des plages de valeurs autorisées évidemment.
