### ISSUE TITLE
Possibilité de visualiser les figures et les PDF dans le navigateur

### ISSUE THREAD

**Issue by claudiodsf** [eost/gissmo#84]
Quand on clique sur le liens d'un document (ex., figures PDF), celui-ci est automatiquement téléchargé.

Cela serait pas mal de l'ouvrir par défaut dans une nouvelle fenêtre ou onglet du navigateur.

**Comment by claudiodsf** [comment]
Super, merci !

**Comment by blankoworld** [comment]
@claudiodsf : attention, la mise à jour se fera durant l'été. Je n'ai pas encore de date précise pour l'instant.
Ma correction : au clic sur un document, ouverture d'un nouvel onglet pour visualisation.
Testé sur Firefox et Chrome.

**Comment by blankoworld** [comment]
La correction sera disponible dans Gissmo 1.9 qui sortira courant août.
