### ISSUE TITLE
Rallongement du nom dans la liste de materiel.

### ISSUE THREAD

**Issue by SebastienBenahmed** [eost/gissmo#86]
Bonjour,
Dans la liste de modems, il apparait juste le type de model mais pas la marque. Serait-t-il possible de mettre plus de détail dans la liste de materiel (Zyxel SBG3300 au lieu de seulement SBG3300...)?

**Comment by blankoworld** [comment]
Ce serait en effet intéressant d'afficher les fabricants des modèles d'équipement.

Après un test rapide, cela n'augmente pas le temps d'affichage de la liste du matériel, comme cela avait pu être le cas dans le passé avec d'autres éléments.

En revanche, si j'ajoute le fabricant du modèle d'équipement avant sa dénomination, le changement sera effectif sur l'ensemble de Gissmo.Cela te convient-il @SebastienBenahmed ?

@mbdb : quel est ton avis sur la question ?

**Comment by SebastienBenahmed** [comment]
Qu'est ce que tu veux dire par "effectif sur l'ensemble de Gissmo" ?

**Comment by blankoworld** [comment]
Tous les endroits dans Gissmo où l'on peut lire un nom de modèle. Quelques uns que j'ai en tête : 

  * sur la liste des équipements
  * sur la page du détail d'un équipement
  * dans les interventions listées sur une station donnée
  * dans la colonne "Filter" sur la liste des équipements (et dont nous parlons dans ce ticket)

**Comment by SebastienBenahmed** [comment]
Cela me convient.

**Comment by blankoworld** [comment]
Le nom du fabricant sera visible à partir de la version 1.9 de Gissmo qui sort courant août.
