### ISSUE TITLE
Listes déroulantes dans la colonne de type de materiel

### ISSUE THREAD

**Issue by SebastienBenahmed** [eost/gissmo#87]
Bonjour,
La liste de materiel commence à être très longue et des listes déroulantes par type de materiel pourraient diminuer la lourdeur visuelle de la page (et soulager la mollette de la souris).

**Comment by blankoworld** [comment]
Nous sommes d'accord sur le fait que la liste de matériel est **vraiment** très longue.
C'est pénible d'aller jusqu'au bout de la liste et il serait intéressant d'avoir une autre méthode.
En revanche je suis perplexe sur la méthode à employer, techniquement parlant. Autant pour le temps à y consacrer que sur le résultat.

En effet, une liste déroulante implique soit l'utilisation de Javascript pour adapter le filtre tout de suite, soit l'utilisation d'un bouton pour valider le choix effectué.
Étant donné que la liste déroulante demande également d'utiliser la molette de la souris, mais aussi la possibilité d'utiliser une barre de défilement, pourquoi ne pas simplement mettre une barre de défilement sur le panneau des filtres tout entier ?
Quelques règles CSS (feuille de style de la page) pourraient faire l'affaire : 

  * réduire la hauteur du cadre "Filter"
  * ajouter une barre de défilement

Ce n'est peut-être pas l'idéal, mais ça permet de réduire la lourdeur visuelle tout en permettant de lister rapidement les types/modèles d'équipement. Sachant que nous allons avoir une interface refaite à neuf à partir de la 2.0, il vaut mieux réduire les modifications effectuées sur la version courante de Gissmo.

@SebastienBenahmed et @mbdb, que pensez-vous de ce type de modifications (réduction du cadre + barre de défilement) ?

**Comment by mbdb** [comment]
Hello,
Je n'y vois pas d'inconvénient, surtout sachant que cette interface évoluera en v2.0
Maxime

**Comment by blankoworld** [comment]
L'amélioration sera uniquement visible à partir de Gissmo 1.9 qui sort courant août.
