### ISSUE TITLE
Interventions d'équipement impliquant un changement de site

### ISSUE THREAD

**Issue by mbdb** [eost/gissmo#89]
Les interventions Buy, Uninstall, Send impliquent un changement de site de l'équipement concerné. Il est possible de laisser le site à l'identique à la déclaration de cette intervention, ce qui est incohérent.

++
M

**Comment by blankoworld** [comment]
Le blocage sera seulement effectif à la sortie de Gissmo 1.9 courant août. D'ici là il faudra prêter attention aux interventions.
