### ISSUE TITLE
Disallow same date on intervention for a given equipment

### ISSUE THREAD

**Issue by blankoworld** [eost/gissmo#90]
These equipments have 2 interventions on the same date:

* 247
* 248
* 249
* 251
* 252
* 253

Problem: They don't have the right state.

Suggestion: You should disallow user to create an intervention at the same date as another one for a given equipment.

PS: To avoid this problem with equipment states, I just change get_last_state() for Equipment object. But it's not enough regarding database consistency.

**Comment by blankoworld** [comment]
@mbdb : have you something to add about this ticket?

**Comment by mbdb** [comment]
Hello,
Suggestion agreed, I think it is already forbidden. This has be done by Martin Dutil on v0.1 database. I don't know how to correct it manually:
stuff has been bought by DT INSU and tested by OREME on same date and same hour, on 2 different places. Can you correct it @blankoworld ?

**Comment by blankoworld** [comment]
Here is what I should do for this ticket:

  * make a migration file to change the given equipment intervention to something acceptable
  * check in clean() method from the form that you can't create 2 interventions with same equipment at the same date (we don't have to check place for that)

**Comment by blankoworld** [comment]
Note : all these equipments give a problem with Intervention 268.

**Comment by blankoworld** [comment]
Bugfix will be available in Gissmo 1.9 next release.
