### ISSUE TITLE
Matériel sans numéro de série

### ISSUE THREAD

**Issue by langlami** [eost/gissmo#92]
Bonjour,
Comment gere t on le matériel pour le quel nous n'avons pas de numéro de série?  Par exemple certain L4C.
Est ce que cela a été déjà abordé? 
Il y a t il une regle ?

Merci.

**Comment by mbdb** [comment]
Bonjour Mickaël,
Le principe de base de Gissmo est que chaque équipement doit avoir un numéro de série. Vous pouvez mettre un numéro de série inventé, et actualiser ce numéro de série par la suite. 
Chez nous, ça nous a forcé à prendre l'habitude de relever systématiquement les numéros de série.
La réponse est donc: pas de règle particulière, si ce n'est qu'il ne peut y avoir 2 équipement du même modèle et avec un même numéro de série (tu ne peux donc pas mettre 10 L4C avec un SN=Inconnu)

Si tu n'as pas d'autres remarques, je fermerai ce ticket dans la journée,
Maxime

**Comment by langlami** [comment]
Re,

D’accord on adoptera une norme “isterre”. Nous avons certains matériels (vieux capteurs L4C) qui n’ont pas de numéro de série.

à bientôt,
Mickael.

—
Mickaël LANGLAIS
-----------------------------------------------------------------------------------
ISTerre - Institut des Sciences de la Terre
Université Grenoble Alpes
CS 40700
38058 GRENOBLE Cedex 9
+33 (0)6 14 83 16 90
+33 (0)4 76 63 52 16
http://www.isterre.fr/Mickael-LANGLAIS
-----------------------------------------------------------------------------------
