### ISSUE TITLE
Paramètres L4C

### ISSUE THREAD

**Issue by langlami** [eost/gissmo#93]
Bonjour,
Il n'y a actuellement pas de parametrage possible pour les L4C dans le système, enfin, j'ai pas trouvé comment faire.
Or il semblerait utile de saisir les paramètres usine si connus, la sensibilité usine, la valeur de résistance de shunt si utilisée, la sensibilité finale ( shunt + impédence entrée numériseur).
Non ?
Mickael.

**Comment by blankoworld** [comment]
En effet, il peut être utile d'avoir des paramètres supplémentaires pour de - nouveaux - matériels.

@mbdb pourrais-tu regarder avec @langlami  quels paramètres ajouter ?

Une fois fait, merci de fermer le ticket si cela est résolu ;)

**Comment by mbdb** [comment]
Mickaël,
Je viens de rajouter les paramètres suivants: Coil Resistance et Shunt Resistance, et de remplir les valeurs standard. Je pense que ces 2 paramètres suffisent. Par contre, Gissmo définit des valeurs par défaut. Quelle est la configuration la plus standard?
Si tu as besoin de rajouter des valeurs pour des configurations moins habituelles, utilisez ce même canal.
Maxime

**Comment by langlami** [comment]
Bonjour Maxime,

Pour le coil voici la liste des valeurs possibles :
500 Ohms (sensitivity 83,5V/m/s)
2000 Ohms (sensitivity 166,9V/m/s)
5500 Ohms (sensitivity 276,8V/m/s) 

Nous avons classiquement des 5500 Ohms


pour le shunt, cela dépend de l’impédance d’entrée du numériseur également. cela peut etre différent pour chaque site d’une valeur infinie (pas de résistance) à quelques KOhms. Ce champs doit être libre donc.

Faut il aussi ajouter le champs sensibilité globale ?

qu’en penses tu ?

merci.
a+
—
Mickaël LANGLAIS
-----------------------------------------------------------------------------------
ISTerre - Institut des Sciences de la Terre
Université Grenoble Alpes
CS 40700
38058 GRENOBLE Cedex 9
+33 (0)6 14 83 16 90
+33 (0)4 76 63 52 16
http://www.isterre.fr/Mickael-LANGLAIS
-----------------------------------------------------------------------------------

**Comment by mbdb** [comment]
Comment se calcule la sensibilité? Est-ce-que c'est strictement dépendant de la valeur de 'coil resistance' et/ou de 'shunt resistance'? Dans ce cas, on ne la met pas si c'est inter-dépendant. Sinon, on rajoute le paramètre 'Sensitivity'. Si vous préférez l'avoir, on peut bien sûr le rajouter, mais on essaye toujours de minimiser le nombre d'infos et ne garder que le strict nécessaire. Il y a déjà suffisamment de coquilles.

J'ai donc mis la valeur 5500R en valeur par défaut du paramètre 'Coil Resistance'.

Par contre, il ne peut y avoir de champ libre dans la liste des paramètres. On peut mettre une valeur 'Other', mais votre information ne sera pas renseignée.

Tu peux m'envoyer une liste de valeurs 'Shunt resistance' (et une valeur par défaut), même si elle est longue. Je peux l'implémenter, ce n'est pas très long. Le jour où vous avez besoin d'une valeur qui n'est pas renseignée, je peux la rajouter dans la liste autorisée.

Maxime

**Comment by langlami** [comment]
Max,

la sensibilité globale se calcule en prenant compte les différents éléments constituant la chaine capteur, + shunt + impédance input. Donc tu as raison pas besoin d’ajouter cela dans la description, le calcul pourra se faire automatiquement au niveau du noeud A qui génère le dataless.

Je ne peux pas te donner à priori une liste de shunt, il faudrait que l’utilisateur puisse le créer, ou avoir un message indiquant de vous contacter pour saisir la valeur. Par défaut dans ce cas le champs pourrait être “oui” ou “non” avec un champs de saisi supp. si le champs est placé à oui. est ce gérable ?

+
—
Mickaël LANGLAIS
-----------------------------------------------------------------------------------
ISTerre - Institut des Sciences de la Terre
Université Grenoble Alpes
CS 40700
38058 GRENOBLE Cedex 9
+33 (0)6 14 83 16 90
+33 (0)4 76 63 52 16
http://www.isterre.fr/Mickael-LANGLAIS
-----------------------------------------------------------------------------------

**Comment by mbdb** [comment]
Je vais voir ce qu'il est envisageable de faire, mais à priori, cette option n'est pas possible dans gissmo. On regarde avec @blankoworld 
Bon week-end
M

**Comment by mbdb** [comment]
On ne peut pas laisser de champ libre. L'idée à terme est qu'une valeur donnée pointe vers une information dataless d'une bibliothèque donnée. Les paramètres doivent être pré-rentrés, et les champ 'Other' doivent être évités.
Il faudra que vous nous contactiez pour rajouter des valeurs.

**Comment by mbdb** [comment]
@blankoworld: Peut-on rajouter une mention (du style 'Contact superuser if other value required') au niveau des Configurations des nouveaux Channels?

**Comment by blankoworld** [comment]
@mbdb : oui nous pouvons trouver une méthode pour afficher un tel message.

**Comment by blankoworld** [comment]
Une aide à l'utilisateur via un point d'interrogation sur le champ "Value" des configurations de canal a été rajouté pour souligner le fait que l'utilisateur peut contacter l'administrateur pour d'éventuelles nouvelles valeurs.

**Comment by blankoworld** [comment]
La modification effectuée sera disponible à la sortie de la prochaine version de Gissmo : 1.9. Courant août.
