### ISSUE TITLE
Définition projet ?

### ISSUE THREAD

**Issue by langlami** [eost/gissmo#94]
J'ai vu qu'il y a une notion de projet dans le système. 
Comment définit on un projet ?

J'ai l'impression que pour ma part je n'accede qu'à trois projets : 
* RESIF-CLB
* Resif
* std_usr
???
Or le systeme oblige à choisir un projet. Pour l'instant j'utilise Resif, mais ce n'est pas forcément toujours correspondant.

merci.

**Comment by blankoworld** [comment]
Je constate en effet un problème d'affiliation sur ton compte, j'ai rajouté RAP, OMIV et AlpArray.

L'idée, c'est à la création d'une station de ne l'ajouter qu'à un projet auquel on participe, pour éviter d'avoir 30 possibilités et ne pas trop savoir dans quoi la mettre.
En l'occurence l'effet inverse est arrivé et je m'en excuse.

Les projets permettent de filtrer les stations dans la liste des stations (Gissmo > Sites, puis dans la colonne Filter by project on clique sur un projet).

Ceci implique que chaque utilisateur rajouté puisse avoir les bons projets attribués. Si par exemple vous ajoutez des CDD dans Gissmo (en demandant à @mbdb), il est intéressant de lui dire aussi à quels projets le CDD participe.
Ceci est valable pour tout autre utilisateur.

Quant à std_user, le mot est mal choisi, c'est un regroupement utile pour le super utilisateur seulement.

Ce que je proposerais donc est de : 

1/ remettre une liste complète des projets proposés afin que chacun puisse choisir le projet auquel il veut rattacher la station
2/ faire en sorte de ne pas voir le groupe std_user

Qu'en dis-tu Mickael ?

**Comment by langlami** [comment]
Bonjour,

Je suis d’accord avec les deux propositions.

Merci.
Mickael.

—
Mickaël LANGLAIS
-----------------------------------------------------------------------------------
ISTerre - Institut des Sciences de la Terre
Université Grenoble Alpes
CS 40700
38058 GRENOBLE Cedex 9
+33 (0)6 14 83 16 90
+33 (0)4 76 63 52 16
http://www.isterre.fr/Mickael-LANGLAIS
-----------------------------------------------------------------------------------

**Comment by douste-bacque** [comment]
Bonjour,
Moi je n'ai pas acces aux rajouts fait pour Mickael.
Je vois RAP, resif-lb RESIF
Merci de mettre les mêmes paramètres aux personnes du même labo.
Bonne journée
Isabelle

**Comment by blankoworld** [comment]
@douste-bacque : J'ai procédé à la modification demandée en utilisant les utilisateurs enregistrés sous le même Labo. Ils ont tous les mêmes projets que @langlami désormais.

**Comment by douste-bacque** [comment]
Ok merci cela fonctionne
Bonne journée
Isabelle

**Comment by blankoworld** [comment]
Cette modification sera effective courant août lors de la sortie de la version 1.9 de Gissmo.
