### ISSUE TITLE
"Nomenclature" des équipements

### ISSUE THREAD

**Issue by langlami** [eost/gissmo#95]
Encore moi, bon après j'arrete.
J'ai eu plusieurs retour de mon équipe de gissmeurs, sur l'hétérogénéité des nomenclatures d'équipements.
Par exemple les mykerinos, il y en a en numériseurs, d'autres en PC industriels. 
Idem dans les noms des kephrens, il y a plusieurs définitions pour le meme produit.
Pareil au niveau des numéros de séries, là on a de tout selon les habitudes de chacun.

Est ce que vous pensez harmoniser cela ?
Est ce que pour éviter ces hétérogénéités cela ne dervait pas être qu'un petit groupe de personne qui puisse créer les nouveaux type d'équipements ?

voila, j'arrete, je l'avais dit au début du message (pour l'instant).

**Comment by mbdb** [comment]
Mickaël,
C'est vrai, l'hétérogénéité des nomenclatures est un souci.
Ceci est un reliquat de l'époque ou les opérateurs rentraient eux-mêmes le modèle des équipements, ce qui a amené à se retrouver à beaucoup de redondance inutile.
Nous avons commencé à normaliser les choses pour les vélocimètres et dataloggers intégrés au réseau FR, mais nous n'avons pas fait le reste. En effet, nous attendons une version figée de la nomenclature, que doit définir le groupe du même nom.

Normaliser la nomenclature n'est pas simple, mais on arrive à forcer les gens à utiliser la nomenclature que l'on souhaite. Par exemple, le modèle STS-2 Gen 1 existe encore en base, mais l'opérateur n'a plus les droits pour l'utiliser, mais peut utiliser la nomenclature normalisée STS-2 (avec un paramètre génération).

De plus le groupe nomenclature ne couvre pas les équipements hors science (batteries, chargeurs, etc...)

Ce que je peux vous proposer, c'est de me faire remonter les modèles d'équipement qui vous gênent, et nous verrons avec @blankoworld si on peut normaliser tout ça de manière plus propre.

Maxime

**Comment by blankoworld** [comment]
@langlami : est-ce bon avec la proposition de @mbdb ?

Je ferme le ticket, rouvrez-le si vous n'êtes pas d'accord avec ce que propose @mbdb.
