### ISSUE TITLE
Config Taurus

### ISSUE THREAD

**Issue by douste-bacque** [eost/gissmo#96]
Bonjour
Dans la config des Taurus, vous affichez 
Taurus : Sample Alignment

Je ne vois pas où se trouve cette information dans la config de la Taurus.
merci
Isabelle

**Comment by mbdb** [comment]
Bonjour Isabelle,

Cela concerne la stratégie de correction en temps des données.
Menu Configuration -> Digitizer -> Timing
Par contre, je ne sais pas pourquoi ce paramètre est noté de cette façon. De plus les valeurs autorisées sont 'None', 'UTC', 'HDR'. Je ne sais pas à quoi ça correspond, ni ce que 'HDR' signifie. Je vais scanner la base pour voir quel canal actif utilise ce paramètre, et voir si on peut les modifier. 
Si on renomme, je te propose de le faire de la façon suivante:
Paramètre: 'Resynchronisation mode'
Valeurs: 'Discard Samples', 'Slow Coarse Lock', 'No Alignment', pour coller à la configuration des Taurus.
La valeur par défaut des Taurus de Sismob que nous recevons est 'Slow Coarse Lock'. Je te propose de garder cette valeur par défaut.

Je te tiens au courant.

Maxime

**Comment by douste-bacque** [comment]
Re-bonjour Maxime
Est-ce que le plus simple ce n'est pas que vous créiez vous les paramètres des stations.
Je n'ai pas de paramètres pour les mykerinos qui sont associées à des numeriseurs Titan.
Lorsque je veux créer une nouvelle configuration j'accède à 2 menus déroulants mais vides .....
Merci de nous tenir au courant.
Bon week end....cela peut attendre lundi
A +

**Comment by blankoworld** [comment]
@mbdb : où cela en est-il ?

**Comment by mbdb** [comment]
Hello,
6 canaux utilisent le paramètre 'Sample Alignment' = 'HDR'.
J'ai mis cette nomenclature dans Gissmo, elle vient bien de quelque part, mais personne n'est capable de me dire ce que c'est exactement. 
Je voudrais m'assurer que c'est bien la même chose que 'Resynchronisation mode'. Est-ce-qu'un utilisateur Taurus (@langlami , ou quelqu'un de Sismob?) peut me dire ce que c'est?

Si je n'ai pas de réponses, et si personne ne sait, je vais faire la chose suivante:
Renommer 'Sample Alignment' en 'Resynchronisation mode'
Rajouter 'Discard Samples', 'Slow Coarse Lock', 'No Alignment' dans les valeurs possibles.

Maxime

**Comment by langlami** [comment]
Salut Maxime, 

Ta proposition me convient. 
M 

-- 
Mickaël LANGLAIS 
---------------------------------------------------------------- 
ISTerre - Institut des Sciences de la Terre 
Université de Grenoble/CNRS 
BP 53 - 38041 Grenoble cedex 9 - FRANCE 
GSM. +33 (0)6 14 83 16 90 
TEL. +33 (0)4 76 63 52 16 
http://www.isterre.fr/Mickael-LANGLAIS 
---------------------------------------------------------------- 


De: "Maxime Bès de Berc" <notifications@github.com> 
À: "eost/gissmo" <gissmo@noreply.github.com> 
Cc: "langlami" <mickael.langlais@univ-grenoble-alpes.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Lundi 12 Juin 2017 10:18:11 
Objet: Re: [eost/gissmo] Config Taurus (#96) 



Hello, 
6 canaux utilisent le paramètre 'Sample Alignment' = 'HDR'. 
J'ai mis cette nomenclature dans Gissmo, elle vient bien de quelque part, mais personne n'est capable de me dire ce que c'est exactement. 
Je voudrais m'assurer que c'est bien la même chose que 'Resynchronisation mode'. Est-ce-qu'un utilisateur Taurus ( @langlami , ou quelqu'un de Sismob?) peut me dire ce que c'est? 

Si je n'ai pas de réponses, et si personne ne sait, je vais faire la chose suivante: 
Renommer 'Sample Alignment' en 'Resynchronisation mode' 
Rajouter 'Discard Samples', 'Slow Coarse Lock', 'No Alignment' dans les valeurs possibles. 

Maxime

**Comment by mbdb** [comment]
Bonjour à tous,
J'ai effectué la correction précisée ci-dessus.
Bonne journée,
Maxime
