### ISSUE TITLE
Dépôt de documents impossible

### ISSUE THREAD

**Issue by mibonnin** [eost/gissmo#98]
Bonjour,

Depuis une dizaine de jour je n'arrive plus à déposer de documents (dossiers, photos) dans la partie «Documents (site)» des sites.
Seuls des fichiers de quelques dizaines de Ko sont acceptés.
Pour les autres une l'erreur suivante apparaît : «413 Request Entity Too Large».

Ceci se produit sur toute les machines au LPG.

Merci d'avance pour toute aide.

**Comment by blankoworld** [comment]
@mibonnin : j'ai une idée de ce que cela peut-être (je rencontre également le problème).

Je regarde avec @fabienengels dès mardi matin.

**Comment by blankoworld** [comment]
@mibonnin : Le problème a été réglé. La limite d'envoi de fichiers est désormais à 50 Mo.
