### ISSUE TITLE
Impossible de modifier les «interventions»

### ISSUE THREAD

**Issue by mibonnin** [eost/gissmo#99]
Bonjour,

Lorsque j'édite et modifie une intervention ayant déjà été sauvegardée (ajouter un intervenant, changer l'heure, le matériel...) il est impossible de sauvegarder les modifications.

L'erreur suivante apparaît : «502 Bad Gateway».

Merci pour votre aide.

**Comment by blankoworld** [comment]
@mibonnin : aurais-tu les détails suivants sur l'intervention dont tu parles : 

  * numéro de l'intervention (en haut dans l'URL, il y a écrit quelque chose comme intervention/intervention/765/change)
  * l'intervenant que tu souhaites ajouter
  * le matériel que tu souhaites ajouter et les actions/états choisis pour ledit matériel

Merci d'avance ;)

**Comment by mibonnin** [comment]
Merci pour ta réponse Olivier.

En fait ça me fait ça sur toutes les interventions.

En guise d'exemple tu peux prendre l'intervention 3813 (site SGFF).
 - Je souhaiterais y ajouter pierrick.gernigon et kemi.kouadio comme intervenants;
 - Concernant le matériel j'aimerais par exemple assigner au capteur (Trillium-120PA : 1126) et au numériseur (Q330S : 4418) une des «places» définie pour le site.

Je ne peux réaliser aucune de ces actions :(

Mickaël

**Comment by blankoworld** [comment]
Je viens en effet de rencontrer le problème qui semble arriver sur les utilisateurs appartenant à plusieurs organismes.

Je me chargerai de résoudre le problème courant de la semaine en vue de la prochaine sortie de GISSMO.

**Comment by blankoworld** [comment]
La correction sera disponible à la sortie de Gissmo 1.9 courant août.
